# rooms = {"Vine of Mire": "The room has a huge vine running up through the ceiling.",
# "Bright Flat": "There is a bright loght comming through the ceiling and shining onto a small pool in the middle of the room.",
# "Ash County": "This room is so large it seem like a country.",
# "Southknoll	": "There is a knoll of grass that seems to have grown around the most southern point in the room.",
# "Goldwood": "A grove of trees with bark a bright shiny yellow.",
# "Inns lake": "This underground lake is vast, but there is boat on the water. you cant see across it.",
# "Archers rock": "THere is a rock in here with a a large whole cut into it. You see a few old arrow heads in inside it.",
# "Owlgreen": "You stumble into a very green area with hundreds of hooting owls. It is pretty creepy.",
# "Valleylock": "You walk into the room and it is as wide as a glacier cravas and as at leas a mile long. ",
# "Helmsrapid": "You walk it and there is a small bridge running accross an underground rapid.",
# "Crystalmoors": "The vast purpl crystals are mesmerizing you could stare at them for hours.",
# "True Strait": "You see the narrow path.",
# "Redcrypt": "You wish you were not colorblind.",
# "Westronwash": "If your car was in this room you would wash it.",
# "Westronhold": "Hold on! Hold on!",
# "Witch Run": "Why are these old ladies signing up for a 5k?",
# "Sorcerers Wilds": "Look out for gandalf, he is a wildman.",
# "Stonedowns": "There is no place like home, or stonedowns.",
# "Elmpeak": "There is now way to open the trapdoor.",
# "Arrach Bridge": "Don't fall off the bridge",
# "Blessed Gorge": "You have stepped into a sacred place.",
# "Mossy road": "The floor is slippery in here, is that moss?",
# "Archerskeep": "You could really use a bow and arrows.",
# "Sparrow hollow": "There is something flying around in here.",
# "Shieldgate": "You don't know why but this room has stalagtites.",
# "Rogue passage": "There are people watching star wars in here.",
# "Stoutmoor": "You wish that you could eat a lot of food right now.",
# "Leechkeep": "The sound of hissing comes from the back of the room.",
# "Cragpeak": "The floor in this room is really bumpy.",
# "Mosspoint": "There is a big x on the floor covered in moss.",
# "Scout Hill": "You found a woodcarving merit badge!!",
# "Grey Divide": "Everything is in grayscale and divided.",
# "Marble Plateau": "This plateau is made of marbles and feels strange under your feet.",
# "Low Ruin": "This ruin is below sea level, so luckily it isn't raining.",
# "Lookout Road": "You look out from your spot on the road and the wind hits you in the face.",
# "Carn River": "You see a slow flowing river with stones piled up on the banks.",
# "Bronzewood Bluff": "You are not bluffing, the trees in here are shiny and brown like bronze.",
# "Dungeon Basin": "There is a basin full of glowing purple liquid that you probably should not touch.",
# "Mud Dome": "The dome is dark and cool inside, a perfect place to rest.",
# "Mink Canyon": "What is that you just heard, it sounds like water.",
# "Mud Divide": "It is just sandy right now.",
# "Long Divide": "This room is sooooo long.",
# "Piratescleft": "There is a statue of a pirate, you don't think it will help you on your quest.",
# "Keelpond": "There are no fish in the pond.",
# "Tunnels of the Phantom Guardian": "You have entered the crypt of the phantom guardian.",
# "Haunt of the Destroyed Monk": "The monk in here is nothing special, he's not even bald!",
# "Burrows of the Spirit Priest": "The priest of spirit is very into yoga!",
# "The Dragon Grotto": "Why does the dragon have to live in a grotto?",
# "The Fire Burrow": "You see your childhood flash before your eyes.",
# "The Lion Tooth Quarter": "Are there animal dentists? You don't think so.",
# "The Raging Pit": "There is a feeling of general rage in this room.",
# "The Courage Cell": "You feel so courageous!",
# "Labyrinth of the Phantom King": "It is said the king was very kind.",
# "Vault of the Furious Dragon": "The dragon gets really mad is you step on his tail.",
# "Grotto of the Dishonored Arachnid": "That spider is so shamefull.",
# "Vault of the Thunder Forest": "Why is it so loud in this room?",
# "The Violent Haunt": "The ghosts in here have been very docile so far.",
# "The Flowing Delve": "You have found the flowing delve!",
# "The Prisoner Quarter": "There are old chains in this room, it looks like some one used to keep captives in here.",
# "The Volcanic Delve": "Don't step in the lava!The room has old hyrogliph paintings a large valcano errupting.",
# "The Crescent Moon Vault": "The light of the moon filters through the roof.",
# "The Sanguine Cells": "There are forlorn squirrells in here.",
# "The Eternal Rest Point": "Wow you are feeling sleepy. Don't die here!",
# "The Eternal Labyrinth": "This is a maze inside a maze.People have gotten lost in the labrynth of this room and never made it, be weery of which way you enter.",
# "The Forsaken Cells": "There is nobody in here...nice more cheese-its for you!his room is teaming with bacteria and viruses.",
# "The Murky Cells": "Super murky and kind of gross inside",
# "The Wailing Tunnels": "Is that moaning mertle?he wind blows through to tunnels and causes a horrendous wailing noise. Or it's ghosts.",
# "The Ogre Caverns": "Strange, the ogre has two eyes.here are huge piles of ogre bones towards the edges of the room.",
# "la Tanière Terrible": "Something is terrible in here. You should probably get out!",
# "la Grotte Cachée": "Wow it is dark in here.",
# "les Cavernes Invisibles": "There seems to be something invisible in here, but you don't know because it's invisible",
# "les Tunnels de Bronze": "Oh no a monster, oh actually it's just a rock.",
# "les Tunnels Brûlés": "You're getting hungry, hopefully there is some food in here.",
# "le Tunnel Sec": "Is it snowing in here?",
# "le Donjon Secret": "This room has 3 walls. Nice!",
# "The Lower Quarters": "This is your favorite room yet!",
# "Cavern of the Fallen Widow": "What was that noise?",
# "The Cold Maze": "You wish you had thought to bring you ipod.",
# "The Collapsing Tomb": "You find a friendly gnome in this room.",
# "The Overhanging Catacomb": "This room has a gravel floor.",
# "The Fractured Chamber": "This is the fracture chamber room.",
# "The Fire Tunnel": "There is no fire in here but you still want to move fast.",
# "Cavern of the Hidden Eagle": "You don't see a hidden eagle but eagles are good at hiding, especialy hidden eagles.",
# "Delve of the Conquered Soldier": "You will never be conquered!",
# "The Chaotic Cavern": "The cave room seems chaotic.",
# "The Infernal Lair": "There is a rug on the floor, you can't move it though.",
# "The Phoenix Pit": "Is that dumbledore?",
# "The Unknown Vault": "The contents of the room are unknown, you'll have to look around.",
# "les Terriers en Cristal": "You hear french music.",
# "la Grotte Dansante": "There is some writing on the wall but you don't know french.",
# "la Caverne Démoniaque": "This cavern is more like a maze, don't get lost.",
# "les Donjons Détruits": "THe room is dark but you find places on the walls were there are lanturns and long wooden table in the middle.",
# "le Terrier d'Arrogance": "There is an inscription on the side of the wall, that says beware the arrogant, for they will only find hardship.",
# "la Tanière Lugubre": "The room is is filled with onld stained paintings, you can see one of them looks like the painting of lake high in the mountains.",
# "le Tunnel Ancien": "This tunnel must be close to the surface because it you can see light coming in through cracks in the ceiling.",
# "le Tunnel d'Hurlement": "This tunnels is windy and has a fewi doors on the sides. some look caved in.",
# "le Repaire du Feu": "This is a vary narrow path, be careful you don't get stuck.",
# "The Lucent Burrow": "Be careful in this room, people tend to lose a bit of themselves in here.",
# "The Mirage Vault": "This vault is filled with crystals. So that are so large and smoothe you can see your reflection in them.",
# "The Wondering Chambers": "THis vast chamber is so high and wide that your not sure which direction you should go. If you continue on will you be able to find your way back?"
# }

rooms={
    "Abafar": "A desert planet located in the Outer Rim with a completely white surface. Known as The Void, the planet is barely populated but is home to massive amounts of rhydonium, a scarce and volatile fuel.",
    "Aeos Prime": "An ocean planet located in the Outer Rim territories. Home to native Aeosians and the site of a former Rebel Alliance base.",
    "Agamar": "A barren, rocky planet in the Outer Rim. Site of a still-active reserve of Separatist droids that became known for surviving the Clone Wars",
    "Ahch-To": "Oceanic planet on which Luke Skywalker has been hiding for several years, and the location of the first Jedi Temple and the Tree Library of sacred Jedi texts. Porgs are among the native species.",
    "Ajan Kloss": "A jungle moon which serves as a new base of operations for the Resistance. Leia Organa dies here after using the last of her energy to reach out to her son through the Force.",
    "Akiva": "Jungle planet and home of Norra and Temmin Wexley, and a primary setting in Aftermath",
    "Alderaan": "	Forests, mountains; home planet of Princess Leia and the House of Organa. Destroyed by the first Death Star as punishment for involvement in the Rebel Alliance and also as a demonstration of power.",
    "Alzoc III": "	Ice planet, with many glaciers, and in its surface lies a crashed separatist carrier, with an anti-gravitational device.",
    "Ando": "A water-covered planet located in the Outer Rim, it is home to the amphibious Aqualish species and endures great turmoil during the Separatist Crisis.",
    "Anoat": "Polluted; A nearly inhospitable planet used by the Empire.",
    "Arvala-7": "An out-of-the-way desert planet where the Mandalorian was sent by the Client to look for the Child and where Kuiil worked as a vapor farmer.",
    "Atollon": "Desert planet, site of Phoenix Squadron Rebel base. Home of the spider-like hexapods known as the Krykna, and the powerful force-wielder Bendu.",
    "Batuu": "A remote frontier outpost and old trading port",
    "Behpour": "A toxic planet where Confederacy of Independent Systems had a secret laboratory commanded by Kul Teska",
    "Bespin": "A gas planet with a thin layer of habitable atmosphere where Cloud City was located. The planet's gas layers were a source of rare tibanna gas which was harvested and refined at mining complexes like Cloud City.",
    "Bogano": "A hospitable planet where Eno Cordova hid from the Empire. There was a structure known as The Vault, within which hid a Jedi holocron.",
    "Bracca": "An inhospitable junkyard planet in the Mid Rim considered strategically important in the Clone Wars. Becomes useful to the Scrapper Guild whose members salvage decommissioned ships for the Empire.",
    "Cantonica": "An arid planet where the resort city of Canto Bight, home of the Canto Casino and Racetrack, is located.",
    "Castilon": "An ocean planet located in the Outer Rim near Wild Space. Home to the aircraft refueling station Colossus, as well as a destination for racers.",
    "Cato Neimoidia": "	The site of battles throughout the Clone Wars, notable for its Bridge Cities. Also the site of Plo Koon's death during the Great Jedi Purge.",
    "Celsor 3": "An uninhabited ice moon and home to the Jakoosk.",
    "Chandrila": "Homeworld of Mon Mothma, it serves as the first capital of the New Republic. Serene planet known for calm seas and rolling hills.",
    "Christophsis": "During the Clone Wars, the Battle of Christophsis occurs here, serving as an introduction to Ahsoka Tano.",
    "Concord Dawn": "Home planet of Jango Fett. Habitable planet that is surrounded by a large amount of debris from many vicious wars. Formerly controlled by the Mandalorians.",
    "Corellia": "Industrial planet located in the Core of the galaxy, with a strong culture of training pilots. Homeworld of Han Solo.",
    "Coruscant": "Cosmopolitan urban world consisting of one planet-wide city. Governmental center of the Galactic Republic and later the Galactic Empire.",
    "Crait": "Small mineral planet located in a remote section of the galaxy, its surface is covered with a layer of white salt over its red-colored soil. In Leia, Princess of Alderaan it is the location of an early Rebel Alliance outpost. Leia and her remaining Resistance forces flee there in The Last Jedi, where they face off with the First Order.",
    "D'Qar": "Site of a Resistance operations base led by General Leia Organa.",
    "Dagobah": "Swamp planet and Yoda's residence after the fall of the Jedi.",
    "Dantooine": "Rural planet and the former site of a Rebel base.",
    "Dandoran": "Lush and watery planet in Hutt space. Home to many smuggling cartels",
    "Dathomir": "Homeworld of the Force-sensitive Nightsisters, including Asajj Ventress. Also the homeworld of the Zabrak warriors, including Darth Maul.",
    "Devaron": "Forest planet with an ancient Jedi Temple.",
    "Eadu": "Rocky, mountainous planet beset by constant severe storms. Home to an Imperial weapons research facility. Its appearance was partly inspired by the fictitious planet LV-426 from the Alien franchis",
    "Endor": "Forest moon that the second Death Star orbits. Inhabited by Ewoks. The location of the battle between the Rebel Alliance and the Empire leading to the destruction of the second Death Star.",
    "Er´kit": "Desert planet located in the galaxy's Outer Rim Territories. Homeworld of the Er'Kit species.",
    "Eriadu": "Planet located in the galaxy's Outer Rim. Homeworld of Grand Moff Tarkin and his fam",
    "Exegol": "A stormy planet in the galaxy's Unknown Regions. An ancient bastion of the Sith, it serves as the lair of Emperor Palpatine during the construction of his armada known as the Final Order.",
    "Felucia": "Jungle planet teeming with plants but little animal life. Aayla Secura is assassinated here during the Jedi Purge.",
    "Florrum": "Sulfurous desert planet. Hondo Ohnaka is the leader of a pirate gang based on the planet.",
    "Fondor": "Imperial manufacturing center with large shipyards.",
    "Geonosis": "Rocky desert planet where battle droids are manufactured, and the site of the opening battle of the Clone Wars. All life on the planet is presumed destroyed by the Empire in Star Wars Rebels, with two exceptions: Klik-Klak and his offspring.[50] Primary construction site of the first Death Star. Homewold of the Geonosians.",
    "Hosnian Prime": "Urban planet and capital of the New Republic.[52] Destroyed by the First Order's Starkiller Base.",
    "Hoth": "Desolate ice planet and base for the Rebel Alliance.",
    "Iego": "An Outer Rim planet which harbors flying creatures called xandu and medicinally important plants called reeska. Iego is surrounded by a 1000 moons and at least one of these, named Millius Prime, is home to a race called the Angels.",
    "Ilum": "Remote ice planet where kyber crystals are mined. It is believed to be the same planet as Starkiller Base",
    "Iridonia": "Rumored birthplace of Darth Maul",
    "Jakku": "Desert planet. Site of a graveyard of ships damaged during the Battle of Jakku, the final battle between the New Republic and the Galactic Empire. Also the homeworld of Rey.",
    "Jedha": "Cold desert moon, and a sacred place for believers in the Force. A source of kyber crystals used for lightsabers and the Death Star's primary weapon. It is also the first location on which the Death Star's destructive capability is tested.",
    "Kamino": "Ocean planet where cloning technology is developed and the Clone Army is created and trained. Obi-Wan Kenobi discovers that the planet is missing from the Jedi archives; it is later revealed to have been deleted as a part of Darth Sidious' plot to start the Clone Wars",
    "Kashyyyk": "Forest planet and home of the Wookiees. Also the site of one of the final battles of the Clone Wars.",
    "Kef Bir": "A moon of Endor and the location of some of the wreckage of the second Death Star after it was destroyed in Return of the Jedi.",
    "Kessel": "A mining planet that has been fought over by crime lords for its valuable Spice. A fissure vent beneath the spice mines served as a source of astatic coaxium, an element that could be refined into hyperfuel for starships.",
    "Kijimi": "A frigid mountainous planet. It was the homeworld of Zorii Bliss, leader of the smuggling gang known as the Spice Runners of Kijimi. It is later destroyed by the Final Order as a show of force for the rest of the galaxy.",
    "Kuat": "Industrial planet home to Kuat Drive Yards, the manufacturer of Star Destroyers.",
    "Lah'mu": "A remote planet with black sands, where Jyn Erso and her parents go into hiding.",
    "Lira San": "The original homeworld of the Lasat, according to Zeb Orrelios, member of the Spectres",
    "Lothal": "Remote farm planet and birthplace of Ezra Bridger.",
    "Lotho Minor": "A planetary junkyard and hiding place of Darth Maul after his presumed death.",
    "Malachor": "Desolate Sith temple world and site of two major battles thousands of year apart: one involving the Scourge of Malachor, the other between Darth Maul, several Rebels, Darth Vader, and several Inquisitors.",
    "Malastare": "Forested planet where podracing is popular. Birthplace of Sebulba and homeworld of the Dug.",
    "Mandalore": "Formerly habitable planet and the subject of legends due to its history of Mandalorian warriors."
}