# Generated by Django 3.0.4 on 2020-03-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_room_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
